export const WS_ACTIONS = {
  // general
  SYSTEM: "system",
  SYSTEM_ACK: "system:ack",
  PING: "ping",
  PONG: "pong",
  ERROR: "error",
  // session
  SESSION_INITIALIZED: "session:initialized",
  SESSION_CLOSED: "session:closed",
  // contact
  CONTACT_IDENTIFIED: "contact:identified",
  CONTACT_UPDATED: "contact:updated",
  CONTACT_QUERY: "contact:query",
  // conversation
  CONVERSATION_CREATED: "conversation:created",
  CONVERSATION_UPDATED: "conversation:updated",
  CONVERSATION_QUERY: "conversation:query",
  CONVERSATION_READ: "conversation:read",
  // participant
  PARTICIPANT_CREATED: "participant:created",
  PARTICIPANT_UPDATED: "participant:updated",
  PARTICIPANT_QUERY: "participant:query",
  // messages
  MESSAGE_CREATED: "message:created",
  MESSAGE_STATUS: "message:status",
  MESSAGE_TRANSCRIPT: "message:transcript",
  MESSAGE_QUERY: "message:query",
  MESSAGE_FEEDBACK: "message:feedback",
  // auth
  AUTH_REQUIRED: "auth:required",
  // connection
  CONNECTION_STARTED: "connection:started",
  CONNECTION_SUCCESS: "connection:success",
  CONNECTION_FAILED: "connection:failed",
  // correlated agent lifecycle UI projections
  AGENT_THINKING: "agent:thinking",
  AGENT_PROCESSING: "agent:processing",
  TOOL_EXECUTING: "tool:executing",
  TOOL_COMPLETED: "tool:completed",
  AGENT_RESPONSE_COMPLETE: "agent:response_complete",
  // webrtc
  WEBRTC_PREPARE: "webrtc:prepare",
  WEBRTC_OFFER: "webrtc:offer",
  WEBRTC_ANSWER: "webrtc:answer",
  WEBRTC_CANDIDATE: "webrtc:ice_candidate",
  WEBRTC_HANGUP: "webrtc:hangup",
  // webrtc state events
  WEBRTC_PEER_CREATED: "webrtc:peer_created",
  WEBRTC_PEER_CONNECTING: "webrtc:peer_connecting",
  WEBRTC_PEER_CONNECTED: "webrtc:peer_connected",
  WEBRTC_PEER_DISCONNECTED: "webrtc:peer_disconnected",
  WEBRTC_PEER_FAILED: "webrtc:peer_failed",
  WEBRTC_ICE_GATHERING: "webrtc:ice_gathering",
  WEBRTC_ICE_COMPLETE: "webrtc:ice_complete",
  WEBRTC_TRACK_ADDED: "webrtc:track_added",
  WEBRTC_TRACK_REMOVED: "webrtc:track_removed",
  // stt state events
  STT_CONNECTING: "stt:connecting",
  STT_CONNECTED: "stt:connected",
  STT_READY: "stt:ready",
  STT_DISCONNECTED: "stt:disconnected",
  STT_ERROR: "stt:error",
  // tts state events
  TTS_CONNECTING: "tts:connecting",
  TTS_CONNECTED: "tts:connected",
  TTS_READY: "tts:ready",
  TTS_DISCONNECTED: "tts:disconnected",
  TTS_ERROR: "tts:error",
  // audio
  AUDIO_CONFIG: "audio:config",
  VOICE_STATE: "voice:state",
} as const;
