"""Explicit Support field contracts for shared SOR audit queries."""

from __future__ import annotations

from collections.abc import Callable

from sqlalchemy.orm import QueryableAttribute

from eylo.sor.shared.contracts import SorProfile
from eylo.sor.shared.models import (
    SorProfileRecordModel,
    SorRecordModel,
    SorSourceModel,
)
from eylo.sor.shared.query import SorGridColumnImportance, SorGridColumnKind
from eylo.sor.shared.reads import SorEntityReadSpec, SorReadFieldSpec

from .models import (
    SupportAgentModel,
    SupportAttachmentModel,
    SupportCustomerModel,
    SupportInboxModel,
    SupportMessageModel,
    SupportQueueModel,
    SupportSlaMetricModel,
    SupportTagModel,
    SupportTicketModel,
)


def _extension_value(
    name: str,
) -> Callable[[SorRecordModel, SorProfileRecordModel | None, SorSourceModel], object]:
    return lambda _record, extension, _source: (
        getattr(extension, name) if extension is not None else None
    )


def _field(
    *,
    key: str,
    label: str,
    kind: SorGridColumnKind,
    importance: SorGridColumnImportance,
    expression: QueryableAttribute[object],
    attribute: str,
    default_visible: bool = True,
    filterable: bool = True,
    sortable: bool = True,
    groupable: bool = False,
    wraps: bool = False,
    reference_entity: str | None = None,
) -> SorReadFieldSpec:
    return SorReadFieldSpec(
        key=key,
        label=label,
        kind=kind,
        importance=importance,
        expression=expression,
        read_value=_extension_value(attribute),
        default_visible=default_visible,
        filterable=filterable,
        sortable=sortable,
        groupable=groupable,
        wraps=wraps,
        reference_entity=reference_entity,
        value_key=attribute,
    )


SUPPORT_TICKET_READ_SPEC = SorEntityReadSpec(
    profile=SorProfile.SUPPORT,
    entity="ticket",
    model=SupportTicketModel,
    fields=(
        _field(
            key="subject",
            label="Subject",
            kind=SorGridColumnKind.LONG_TEXT,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportTicketModel.subject,
            attribute="subject",
            wraps=True,
        ),
        _field(
            key="status",
            label="Status",
            kind=SorGridColumnKind.ENUM,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportTicketModel.normalized_status,
            attribute="normalized_status",
            groupable=True,
        ),
        _field(
            key="requester",
            label="Requester",
            kind=SorGridColumnKind.REFERENCE,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportTicketModel.requester_external_id,
            attribute="requester_external_id",
            groupable=True,
            reference_entity="customer",
        ),
        _field(
            key="priority",
            label="Priority",
            kind=SorGridColumnKind.ENUM,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportTicketModel.priority,
            attribute="priority",
            groupable=True,
        ),
        _field(
            key="assignee",
            label="Assignee",
            kind=SorGridColumnKind.REFERENCE,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportTicketModel.assignee_external_id,
            attribute="assignee_external_id",
            groupable=True,
            reference_entity="agent",
        ),
        _field(
            key="queue",
            label="Queue",
            kind=SorGridColumnKind.REFERENCE,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportTicketModel.group_external_id,
            attribute="group_external_id",
            groupable=True,
            reference_entity="queue",
        ),
        _field(
            key="inbox",
            label="Inbox",
            kind=SorGridColumnKind.REFERENCE,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportTicketModel.inbox_external_id,
            attribute="inbox_external_id",
            default_visible=False,
            groupable=True,
            reference_entity="inbox",
        ),
        _field(
            key="category",
            label="Category",
            kind=SorGridColumnKind.ENUM,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportTicketModel.category,
            attribute="category",
            default_visible=False,
            groupable=True,
        ),
        _field(
            key="channel",
            label="Channel",
            kind=SorGridColumnKind.ENUM,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportTicketModel.channel,
            attribute="channel",
            default_visible=False,
            groupable=True,
        ),
        _field(
            key="tags",
            label="Tags",
            kind=SorGridColumnKind.STRING_ARRAY,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportTicketModel.tag_external_ids,
            attribute="tag_external_ids",
            sortable=False,
            wraps=True,
            reference_entity="tag",
        ),
        _field(
            key="sla_state",
            label="SLA state",
            kind=SorGridColumnKind.ENUM,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportTicketModel.sla_state,
            attribute="sla_state",
            default_visible=False,
            groupable=True,
        ),
        _field(
            key="first_response_at",
            label="First response",
            kind=SorGridColumnKind.DATETIME,
            importance=SorGridColumnImportance.METADATA,
            expression=SupportTicketModel.first_response_at,
            attribute="first_response_at",
            default_visible=False,
        ),
        _field(
            key="resolved_at",
            label="Resolved",
            kind=SorGridColumnKind.DATETIME,
            importance=SorGridColumnImportance.METADATA,
            expression=SupportTicketModel.resolved_at,
            attribute="resolved_at",
            default_visible=False,
        ),
        _field(
            key="closed_at",
            label="Closed",
            kind=SorGridColumnKind.DATETIME,
            importance=SorGridColumnImportance.METADATA,
            expression=SupportTicketModel.closed_at,
            attribute="closed_at",
            default_visible=False,
        ),
        _field(
            key="native_status",
            label="Source status",
            kind=SorGridColumnKind.ENUM,
            importance=SorGridColumnImportance.METADATA,
            expression=SupportTicketModel.native_status,
            attribute="native_status",
            default_visible=False,
            groupable=True,
        ),
        _field(
            key="description",
            label="Description",
            kind=SorGridColumnKind.LONG_TEXT,
            importance=SorGridColumnImportance.METADATA,
            expression=SupportTicketModel.normalized_description,
            attribute="normalized_description",
            default_visible=False,
            wraps=True,
        ),
    ),
)

SUPPORT_CUSTOMER_READ_SPEC = SorEntityReadSpec(
    profile=SorProfile.SUPPORT,
    entity="customer",
    model=SupportCustomerModel,
    fields=(
        _field(
            key="name",
            label="Name",
            kind=SorGridColumnKind.TEXT,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportCustomerModel.name,
            attribute="name",
        ),
        _field(
            key="email",
            label="Email",
            kind=SorGridColumnKind.TEXT,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportCustomerModel.primary_email,
            attribute="primary_email",
        ),
        _field(
            key="phone",
            label="Phone",
            kind=SorGridColumnKind.TEXT,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportCustomerModel.primary_phone,
            attribute="primary_phone",
        ),
        _field(
            key="company",
            label="Company",
            kind=SorGridColumnKind.REFERENCE,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportCustomerModel.company_external_id,
            attribute="company_external_id",
            groupable=True,
        ),
        _field(
            key="active",
            label="Active",
            kind=SorGridColumnKind.BOOLEAN,
            importance=SorGridColumnImportance.METADATA,
            expression=SupportCustomerModel.active,
            attribute="active",
            groupable=True,
        ),
    ),
)

SUPPORT_AGENT_READ_SPEC = SorEntityReadSpec(
    profile=SorProfile.SUPPORT,
    entity="agent",
    model=SupportAgentModel,
    fields=(
        _field(
            key="name",
            label="Name",
            kind=SorGridColumnKind.TEXT,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportAgentModel.name,
            attribute="name",
        ),
        _field(
            key="email",
            label="Email",
            kind=SorGridColumnKind.TEXT,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportAgentModel.primary_email,
            attribute="primary_email",
        ),
        _field(
            key="active",
            label="Active",
            kind=SorGridColumnKind.BOOLEAN,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportAgentModel.active,
            attribute="active",
            groupable=True,
        ),
        _field(
            key="assignable",
            label="Assignable",
            kind=SorGridColumnKind.BOOLEAN,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportAgentModel.assignable,
            attribute="assignable",
            groupable=True,
        ),
        _field(
            key="avatar_url",
            label="Avatar",
            kind=SorGridColumnKind.LINK,
            importance=SorGridColumnImportance.METADATA,
            expression=SupportAgentModel.avatar_url,
            attribute="avatar_url",
            default_visible=False,
        ),
    ),
)

SUPPORT_QUEUE_READ_SPEC = SorEntityReadSpec(
    profile=SorProfile.SUPPORT,
    entity="queue",
    model=SupportQueueModel,
    fields=(
        _field(
            key="name",
            label="Name",
            kind=SorGridColumnKind.TEXT,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportQueueModel.name,
            attribute="name",
        ),
        _field(
            key="description",
            label="Description",
            kind=SorGridColumnKind.LONG_TEXT,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportQueueModel.description,
            attribute="description",
            default_visible=False,
            wraps=True,
        ),
        _field(
            key="active",
            label="Active",
            kind=SorGridColumnKind.BOOLEAN,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportQueueModel.active,
            attribute="active",
            groupable=True,
        ),
    ),
)

SUPPORT_INBOX_READ_SPEC = SorEntityReadSpec(
    profile=SorProfile.SUPPORT,
    entity="inbox",
    model=SupportInboxModel,
    fields=(
        _field(
            key="name",
            label="Name",
            kind=SorGridColumnKind.TEXT,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportInboxModel.name,
            attribute="name",
        ),
        _field(
            key="kind",
            label="Kind",
            kind=SorGridColumnKind.ENUM,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportInboxModel.kind,
            attribute="kind",
            groupable=True,
        ),
        _field(
            key="active",
            label="Active",
            kind=SorGridColumnKind.BOOLEAN,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportInboxModel.active,
            attribute="active",
            groupable=True,
        ),
    ),
)

SUPPORT_MESSAGE_READ_SPEC = SorEntityReadSpec(
    profile=SorProfile.SUPPORT,
    entity="message",
    model=SupportMessageModel,
    fields=(
        _field(
            key="ticket",
            label="Ticket",
            kind=SorGridColumnKind.REFERENCE,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportMessageModel.ticket_external_id,
            attribute="ticket_external_id",
            groupable=True,
            reference_entity="ticket",
        ),
        _field(
            key="text",
            label="Message",
            kind=SorGridColumnKind.LONG_TEXT,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportMessageModel.normalized_text,
            attribute="normalized_text",
            wraps=True,
        ),
        _field(
            key="visibility",
            label="Visibility",
            kind=SorGridColumnKind.ENUM,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportMessageModel.visibility,
            attribute="visibility",
            groupable=True,
        ),
        _field(
            key="direction",
            label="Direction",
            kind=SorGridColumnKind.ENUM,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportMessageModel.direction,
            attribute="direction",
            groupable=True,
        ),
        _field(
            key="author",
            label="Author",
            kind=SorGridColumnKind.REFERENCE,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportMessageModel.author_external_id,
            attribute="author_external_id",
            groupable=True,
        ),
        _field(
            key="attachments",
            label="Attachments",
            kind=SorGridColumnKind.STRING_ARRAY,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportMessageModel.attachment_external_ids,
            attribute="attachment_external_ids",
            default_visible=False,
            sortable=False,
            wraps=True,
            reference_entity="attachment",
        ),
        _field(
            key="created_at",
            label="Created",
            kind=SorGridColumnKind.DATETIME,
            importance=SorGridColumnImportance.METADATA,
            expression=SupportMessageModel.source_created_at,
            attribute="source_created_at",
        ),
        _field(
            key="updated_at",
            label="Updated",
            kind=SorGridColumnKind.DATETIME,
            importance=SorGridColumnImportance.METADATA,
            expression=SupportMessageModel.source_updated_at,
            attribute="source_updated_at",
            default_visible=False,
        ),
        _field(
            key="body_format",
            label="Body format",
            kind=SorGridColumnKind.ENUM,
            importance=SorGridColumnImportance.METADATA,
            expression=SupportMessageModel.body_format,
            attribute="body_format",
            default_visible=False,
            groupable=True,
        ),
    ),
)

SUPPORT_TAG_READ_SPEC = SorEntityReadSpec(
    profile=SorProfile.SUPPORT,
    entity="tag",
    model=SupportTagModel,
    fields=(
        _field(
            key="name",
            label="Name",
            kind=SorGridColumnKind.TEXT,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportTagModel.name,
            attribute="name",
        ),
    ),
)

SUPPORT_SLA_METRIC_READ_SPEC = SorEntityReadSpec(
    profile=SorProfile.SUPPORT,
    entity="sla_metric",
    model=SupportSlaMetricModel,
    fields=(
        _field(
            key="ticket",
            label="Ticket",
            kind=SorGridColumnKind.REFERENCE,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportSlaMetricModel.ticket_external_id,
            attribute="ticket_external_id",
            groupable=True,
            reference_entity="ticket",
        ),
        _field(
            key="metric",
            label="Metric",
            kind=SorGridColumnKind.TEXT,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportSlaMetricModel.metric,
            attribute="metric",
            groupable=True,
        ),
        _field(
            key="state",
            label="State",
            kind=SorGridColumnKind.ENUM,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportSlaMetricModel.normalized_state,
            attribute="normalized_state",
            groupable=True,
        ),
        _field(
            key="value",
            label="Value",
            kind=SorGridColumnKind.NUMBER,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportSlaMetricModel.value,
            attribute="value",
        ),
        _field(
            key="unit",
            label="Unit",
            kind=SorGridColumnKind.ENUM,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportSlaMetricModel.unit,
            attribute="unit",
            groupable=True,
        ),
        _field(
            key="target_at",
            label="Target",
            kind=SorGridColumnKind.DATETIME,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportSlaMetricModel.target_at,
            attribute="target_at",
        ),
        _field(
            key="achieved_at",
            label="Achieved",
            kind=SorGridColumnKind.DATETIME,
            importance=SorGridColumnImportance.METADATA,
            expression=SupportSlaMetricModel.achieved_at,
            attribute="achieved_at",
            default_visible=False,
        ),
        _field(
            key="breached_at",
            label="Breached",
            kind=SorGridColumnKind.DATETIME,
            importance=SorGridColumnImportance.METADATA,
            expression=SupportSlaMetricModel.breached_at,
            attribute="breached_at",
            default_visible=False,
        ),
        _field(
            key="native_state",
            label="Source state",
            kind=SorGridColumnKind.ENUM,
            importance=SorGridColumnImportance.METADATA,
            expression=SupportSlaMetricModel.native_state,
            attribute="native_state",
            default_visible=False,
            groupable=True,
        ),
    ),
)

SUPPORT_ATTACHMENT_READ_SPEC = SorEntityReadSpec(
    profile=SorProfile.SUPPORT,
    entity="attachment",
    model=SupportAttachmentModel,
    fields=(
        _field(
            key="name",
            label="Name",
            kind=SorGridColumnKind.TEXT,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportAttachmentModel.name,
            attribute="name",
        ),
        _field(
            key="ticket",
            label="Ticket",
            kind=SorGridColumnKind.REFERENCE,
            importance=SorGridColumnImportance.PRIMARY,
            expression=SupportAttachmentModel.ticket_external_id,
            attribute="ticket_external_id",
            groupable=True,
            reference_entity="ticket",
        ),
        _field(
            key="message",
            label="Message",
            kind=SorGridColumnKind.REFERENCE,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportAttachmentModel.message_external_id,
            attribute="message_external_id",
            groupable=True,
            reference_entity="message",
        ),
        _field(
            key="content_type",
            label="Content type",
            kind=SorGridColumnKind.ENUM,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportAttachmentModel.content_type,
            attribute="content_type",
            groupable=True,
        ),
        _field(
            key="size_bytes",
            label="Size",
            kind=SorGridColumnKind.NUMBER,
            importance=SorGridColumnImportance.SECONDARY,
            expression=SupportAttachmentModel.size_bytes,
            attribute="size_bytes",
        ),
        _field(
            key="source_url",
            label="Source file",
            kind=SorGridColumnKind.LINK,
            importance=SorGridColumnImportance.METADATA,
            expression=SupportAttachmentModel.source_url,
            attribute="source_url",
            default_visible=False,
        ),
    ),
)

SUPPORT_READ_SPECS = {
    spec.entity: spec
    for spec in (
        SUPPORT_TICKET_READ_SPEC,
        SUPPORT_CUSTOMER_READ_SPEC,
        SUPPORT_AGENT_READ_SPEC,
        SUPPORT_QUEUE_READ_SPEC,
        SUPPORT_INBOX_READ_SPEC,
        SUPPORT_MESSAGE_READ_SPEC,
        SUPPORT_TAG_READ_SPEC,
        SUPPORT_SLA_METRIC_READ_SPEC,
        SUPPORT_ATTACHMENT_READ_SPEC,
    )
}


__all__ = [
    "SUPPORT_AGENT_READ_SPEC",
    "SUPPORT_ATTACHMENT_READ_SPEC",
    "SUPPORT_CUSTOMER_READ_SPEC",
    "SUPPORT_INBOX_READ_SPEC",
    "SUPPORT_MESSAGE_READ_SPEC",
    "SUPPORT_QUEUE_READ_SPEC",
    "SUPPORT_READ_SPECS",
    "SUPPORT_SLA_METRIC_READ_SPEC",
    "SUPPORT_TAG_READ_SPEC",
    "SUPPORT_TICKET_READ_SPEC",
]
