"""Eylo-native LLM framework primitives.

This package defines contracts for the framework execution path.
"""

from .agent import AgentSpec
from .approval import (
    ApprovalActionKind,
    ApprovalDecision,
    ApprovalDecisionKind,
    ApprovalRequest,
    ApprovalRequestStatus,
    RiskLevel,
)
from .config import RunConfig, RunPromptCaching, RunStreaming, RunTracing
from .context import RunContext, RunInput, RunMessage
from .durable import (
    DurableInterruption,
    DurableRun,
    DurableRunKind,
    DurableRunStatus,
    InputRequest,
    InputRequestDetails,
    InputRequestStatus,
    ProgressUpdate,
    RunCheckpoint,
)
from .errors import (
    ApprovalRequiredError,
    FrameworkError,
    GuardrailTripwireError,
    MaxTurnsExceededError,
    ModelOutputLimitError,
    RunTimeoutError,
    SandboxPolicyError,
    ToolResultIdentityError,
)
from .feature import (
    FeatureAgentBinding,
    FeatureArtifact,
    FeatureArtifactKind,
    FeatureSignal,
    FeatureSignalKind,
)
from .guardrail import (
    Guardrail,
    GuardrailResult,
    GuardrailSpec,
    GuardrailStage,
)
from .handoff import HandoffResult, HandoffSpec
from .hooks import RunCallbacks, RunHooks
from .interruptions import (
    RunApprovalInterruption,
    RunInputInterruption,
    ToolApprovalContinuation,
    ToolContinuationKind,
    ToolInputContinuation,
    ToolInputRequestMetadata,
)
from .items import (
    RunApprovalRequestItem,
    RunInputRequestItem,
    RunItem,
    RunItemKind,
    RunMessageItem,
    RunMessagePayload,
    RunSignalItem,
    RunToolCallItem,
    RunToolResultItem,
)
from .model import (
    Model,
    ModelBlockKind,
    ModelOutputBlock,
    ModelReasoningBlock,
    ModelResponse,
    ModelSettings,
    ModelStopReason,
    ModelTextBlock,
    ModelToolCallBlock,
    ModelUsage,
)
from .result import RunFailureCode, RunFailureMetadata, RunResult, RunStatus
from .runner import FrameworkRunner
from .sandbox import (
    SandboxActionDecision,
    SandboxArtifact,
    SandboxArtifactKind,
    SandboxNetworkPolicy,
    SandboxPolicy,
    SandboxRuntimeKind,
    SandboxSession,
    SandboxSessionStatus,
    SandboxSpec,
)
from .sandbox_runtime import (
    SANDBOX_EXEC_TOOL,
    SANDBOX_LIST_ARTIFACTS_TOOL,
    SANDBOX_READ_FILE_TOOL,
    SANDBOX_WRITE_FILE_TOOL,
    LocalWorkspaceSandboxProvider,
    SandboxActionResult,
    SandboxActionStatus,
    SandboxCommand,
    SandboxCommandResult,
    SandboxController,
    SandboxFileWrite,
    SandboxProvider,
    SandboxToolExecutor,
    sandbox_tool_specs,
)
from .session import Session, SessionSnapshot
from .tool import (
    ToolCall,
    ToolExecutionMode,
    ToolExecutor,
    ToolKind,
    ToolResult,
    ToolSpec,
)

__all__ = [
    "AgentSpec",
    "ApprovalActionKind",
    "ApprovalDecision",
    "ApprovalDecisionKind",
    "ApprovalRequest",
    "ApprovalRequestStatus",
    "ApprovalRequiredError",
    "DurableInterruption",
    "DurableRun",
    "DurableRunKind",
    "DurableRunStatus",
    "FeatureAgentBinding",
    "FeatureArtifact",
    "FeatureArtifactKind",
    "FeatureSignal",
    "FeatureSignalKind",
    "FrameworkError",
    "FrameworkRunner",
    "Guardrail",
    "GuardrailResult",
    "GuardrailSpec",
    "GuardrailStage",
    "GuardrailTripwireError",
    "HandoffResult",
    "HandoffSpec",
    "InputRequest",
    "InputRequestDetails",
    "InputRequestStatus",
    "MaxTurnsExceededError",
    "Model",
    "ModelBlockKind",
    "ModelOutputBlock",
    "ModelOutputLimitError",
    "ModelReasoningBlock",
    "ModelTextBlock",
    "ModelToolCallBlock",
    "ModelResponse",
    "ModelSettings",
    "ModelStopReason",
    "ModelUsage",
    "ProgressUpdate",
    "RiskLevel",
    "RunCallbacks",
    "RunApprovalInterruption",
    "RunInputInterruption",
    "RunApprovalRequestItem",
    "RunInputRequestItem",
    "RunMessageItem",
    "RunMessagePayload",
    "ToolApprovalContinuation",
    "ToolContinuationKind",
    "ToolInputContinuation",
    "ToolInputRequestMetadata",
    "RunCheckpoint",
    "RunConfig",
    "RunPromptCaching",
    "RunStreaming",
    "RunTracing",
    "RunContext",
    "RunHooks",
    "RunInput",
    "RunItem",
    "RunItemKind",
    "RunSignalItem",
    "RunToolCallItem",
    "RunToolResultItem",
    "ToolResultIdentityError",
    "RunMessage",
    "RunFailureCode",
    "RunFailureMetadata",
    "RunResult",
    "RunStatus",
    "RunTimeoutError",
    "SANDBOX_EXEC_TOOL",
    "SANDBOX_LIST_ARTIFACTS_TOOL",
    "SANDBOX_READ_FILE_TOOL",
    "SANDBOX_WRITE_FILE_TOOL",
    "SandboxActionDecision",
    "SandboxActionResult",
    "SandboxActionStatus",
    "SandboxArtifact",
    "SandboxArtifactKind",
    "SandboxCommand",
    "SandboxCommandResult",
    "SandboxController",
    "SandboxFileWrite",
    "SandboxNetworkPolicy",
    "SandboxPolicy",
    "SandboxPolicyError",
    "SandboxProvider",
    "SandboxRuntimeKind",
    "SandboxSession",
    "SandboxSessionStatus",
    "SandboxSpec",
    "SandboxToolExecutor",
    "LocalWorkspaceSandboxProvider",
    "Session",
    "SessionSnapshot",
    "ToolCall",
    "ToolExecutionMode",
    "ToolExecutor",
    "ToolKind",
    "ToolResult",
    "ToolSpec",
    "sandbox_tool_specs",
]
