"""Typed next-turn history, separate from executor-private tool annotations."""

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import (
    ConfigDict,
    Field,
    JsonValue,
    SerializerFunctionWrapHandler,
    StrictBool,
    StrictStr,
    field_serializer,
    field_validator,
    model_serializer,
)

from .common import FrameworkMetadata, FrozenFrameworkModel, JsonObject
from .context import RunMessage
from .errors import ToolResultIdentityError
from .model import ModelResponse
from .tool import ToolCall, ToolIdentity, ToolResult


class ModelResponseProvenance(FrozenFrameworkModel):
    """One response authority; older flattened/duplicate wire fields are projections.

    Readback ignores those compatibility copies, using ``model_response`` as the
    source. Serialization regenerates all copies from the same validated model.
    """

    model_config = ConfigDict(
        extra="ignore", revalidate_instances="always", hide_input_in_errors=True
    )

    model_response: ModelResponse
    response_block_index: int | None = Field(default=None, strict=True, ge=0)

    @model_serializer(mode="wrap")
    def serialize_provenance(
        self, handler: SerializerFunctionWrapHandler
    ) -> JsonObject:
        payload = handler(self)
        response = payload.pop("model_response", None)
        if response is None:
            return payload
        return {
            **response,
            "framework": True,
            "llm_response": response,
            "model_response": response,
            **payload,
        }


class ToolResultProvenance(FrozenFrameworkModel):
    """Public result annotations; terminal output and excluded fields stay private."""

    model_config = ConfigDict(
        allow_inf_nan=False,
        revalidate_instances="always",
        hide_input_in_errors=True,
    )

    framework: Literal[True] = True
    tool_call_id: ToolIdentity
    is_error: StrictBool
    metadata: dict[str, JsonValue] = Field(default_factory=dict)

    @classmethod
    def from_result(cls, result: ToolResult) -> ToolResultProvenance:
        return cls(
            tool_call_id=result.tool_call_id,
            is_error=result.is_error,
            metadata=result.metadata.model_dump(
                mode="json", exclude={"terminal_output"}
            ),
        )


class ToolResultMessageData(FrozenFrameworkModel):
    """Named model-facing result, without executor metadata or runtime resources."""

    model_config = ConfigDict(
        allow_inf_nan=False,
        revalidate_instances="always",
        hide_input_in_errors=True,
    )

    tool_call_id: ToolIdentity
    name: ToolIdentity
    is_error: StrictBool
    content: str | dict[str, JsonValue] | list[JsonValue]


class HistoryMessageMetadata(FrameworkMetadata):
    """Caller-owned correlation; platform UUID rules stay outside the framework."""

    model_config = ConfigDict(revalidate_instances="always", hide_input_in_errors=True)

    request_id: StrictStr | UUID | None = None

    @field_validator("request_id", mode="before")
    @classmethod
    def empty_request_is_absent(cls, value: object) -> object:
        """Preserve the existing empty-string sentinel without coercing objects."""
        return None if isinstance(value, str) and value == "" else value

    @model_serializer(mode="wrap")
    def serialize_history_metadata(
        self, handler: SerializerFunctionWrapHandler
    ) -> JsonObject:
        payload = handler(self)
        for name in type(self).model_fields:
            if name not in self.model_fields_set:
                payload.pop(name, None)
        return payload


class ModelMessageMetadata(HistoryMessageMetadata):
    """Text generated by one response block."""

    meta: ModelResponseProvenance


class ToolCallMessageMetadata(HistoryMessageMetadata):
    """Invocation history stores command fields, never executor annotations."""

    tool_call: ToolCall
    meta: ModelResponseProvenance | None = None

    @field_validator("tool_call", mode="after")
    @classmethod
    def public_invocation(cls, call: ToolCall) -> ToolCall:
        """Do not retain executor annotations in model-facing live history either."""
        return call.model_copy(update={"metadata": FrameworkMetadata()})

    @field_serializer("tool_call", mode="wrap")
    def serialize_tool_call(
        self, call: ToolCall, handler: SerializerFunctionWrapHandler
    ) -> JsonObject:
        payload = handler(call.model_copy(update={"metadata": FrameworkMetadata()}))
        payload.pop("metadata", None)
        return payload


class ToolResultMessageMetadata(HistoryMessageMetadata):
    """Model-facing result paired with its call, optionally with provenance."""

    tool_result: ToolResultMessageData
    meta: ToolResultProvenance | None = None


def tool_exchange_messages(
    call: ToolCall,
    result: ToolResult,
    *,
    request_id: str | UUID | None,
    result_text: str,
    model_meta: ModelResponseProvenance | None = None,
    result_meta: ToolResultProvenance | None = None,
) -> tuple[RunMessage, RunMessage]:
    """Build an exact call/result pair without choosing persistence or text format."""
    call = ToolCall.model_validate(call)
    result = ToolResult.model_validate(result)
    if result.tool_call_id != call.id:
        raise ToolResultIdentityError("History tool result does not match its call.")
    call_metadata = ToolCallMessageMetadata(request_id=request_id, tool_call=call)
    result_metadata = ToolResultMessageMetadata(
        request_id=request_id,
        tool_result=ToolResultMessageData(
            tool_call_id=result.tool_call_id,
            name=call.name,
            is_error=result.is_error,
            content=result.content,
        ),
    )
    if model_meta is not None:
        call_metadata = ToolCallMessageMetadata(
            request_id=request_id, tool_call=call, meta=model_meta
        )
    if result_meta is not None:
        result_metadata = ToolResultMessageMetadata(
            request_id=request_id,
            tool_result=result_metadata.tool_result,
            meta=result_meta,
        )
    return (
        RunMessage(
            role="assistant", content=f"Tool call: {call.name}", metadata=call_metadata
        ),
        RunMessage(role="tool", content=result_text, metadata=result_metadata),
    )
