services:
  eylo-server:
    volumes:
      - ${EYLO_DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock

  worker:
    volumes:
      - ${EYLO_DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
