"""Closed platform event names shared by user-session timeline producers."""

from enum import StrEnum


class ProviderTimelineState(StrEnum):
    """Connection observations shared by voice provider timeline producers."""

    CONNECTED = "connected"
    DISCONNECTED = "disconnected"
    FAILED = "failed"


class SessionTimelineEvent(StrEnum):
    """Stored event identities; presentation and payload policy belong to sessions."""

    USER_SESSION_STARTED = "user.session.started"
    USER_SESSION_RECONNECTED = "user.session.reconnected"
    USER_SESSION_DISCONNECTED = "user.session.disconnected"
    USER_SESSION_ENDED = "user.session.ended"
    USER_SESSION_FAILED = "user.session.failed"
    CONVERSATION_STARTED = "conversation.started"
    CONVERSATION_CONTINUED = "conversation.continued"
    MESSAGE_CREATED = "message.created"
    MESSAGE_REQUEST_PROCESSING = "message.request.processing"
    MESSAGE_REQUEST_AWAITING_TOOL_RESULTS = "message.request.awaiting_tool_results"
    MESSAGE_REQUEST_COMPLETED = "message.request.completed"
    MESSAGE_REQUEST_FAILED = "message.request.failed"
    MESSAGE_REQUEST_INTERRUPTED = "message.request.interrupted"
    MESSAGE_REQUEST_SKIPPED = "message.request.skipped"
    AGENT_RUN_QUEUED = "agent.run.queued"
    AGENT_RUN_STARTED = "agent.run.started"
    AGENT_RUN_WAITING_FOR_INPUT = "agent.run.waiting_for_input"
    AGENT_RUN_WAITING_FOR_APPROVAL = "agent.run.waiting_for_approval"
    AGENT_RUN_WAITING_FOR_TOOL = "agent.run.waiting_for_tool"
    AGENT_RUN_RESUMED = "agent.run.resumed"
    AGENT_RUN_COMPLETED = "agent.run.completed"
    AGENT_RUN_FAILED = "agent.run.failed"
    AGENT_RUN_CANCELLATION_REQUESTED = "agent.run.cancellation_requested"
    AGENT_RUN_CANCELLED = "agent.run.cancelled"
    AGENT_INPUT_REQUESTED = "agent.input.requested"
    AGENT_INPUT_RECEIVED = "agent.input.received"
    AGENT_TOOL_STARTED = "agent.tool.started"
    AGENT_TOOL_COMPLETED = "agent.tool.completed"
    AGENT_TOOL_FAILED = "agent.tool.failed"
    AGENT_HANDOFF_COMPLETED = "agent.handoff.completed"
    KNOWLEDGE_FILE_ACCEPTED = "knowledge.file.accepted"
    KNOWLEDGE_INGESTION_QUEUED = "knowledge.ingestion.queued"
    KNOWLEDGE_INGESTION_STARTED = "knowledge.ingestion.started"
    KNOWLEDGE_INGESTION_COMPLETED = "knowledge.ingestion.completed"
    KNOWLEDGE_INGESTION_FAILED = "knowledge.ingestion.failed"
    KNOWLEDGE_INGESTION_CANCELLED = "knowledge.ingestion.cancelled"
    VOICE_SESSION_STARTED = "voice.session.started"
    VOICE_SESSION_ENDED = "voice.session.ended"
    VOICE_USER_INTERRUPTED_AGENT = "voice.user.interrupted_agent"
    VOICE_RECORDING_QUEUED = "voice.recording.queued"
    VOICE_RECORDING_AVAILABLE = "voice.recording.available"
    VOICE_RECORDING_FAILED = "voice.recording.failed"
    TELEPHONY_CALL_STARTED = "telephony.call.started"
    TELEPHONY_CALL_RINGING = "telephony.call.ringing"
    TELEPHONY_CALL_ANSWERED = "telephony.call.answered"
    TELEPHONY_CALL_STATUS_CHANGED = "telephony.call.status_changed"
    TELEPHONY_CALL_TRANSFERRED = "telephony.call.transferred"
    TELEPHONY_CALL_ENDED = "telephony.call.ended"
    TRANSPORT_WEBSOCKET_CONNECTED = "transport.websocket.connected"
    TRANSPORT_WEBSOCKET_DISCONNECTED = "transport.websocket.disconnected"
    TRANSPORT_WEBSOCKET_FAILED = "transport.websocket.failed"
    TRANSPORT_WEBRTC_CONNECTING = "transport.webrtc.connecting"
    TRANSPORT_WEBRTC_CONNECTED = "transport.webrtc.connected"
    TRANSPORT_WEBRTC_DISCONNECTED = "transport.webrtc.disconnected"
    TRANSPORT_WEBRTC_FAILED = "transport.webrtc.failed"
    PROVIDER_STT_CONNECTED = "provider.stt.connected"
    PROVIDER_STT_DISCONNECTED = "provider.stt.disconnected"
    PROVIDER_STT_FAILED = "provider.stt.failed"
    PROVIDER_TTS_CONNECTED = "provider.tts.connected"
    PROVIDER_TTS_DISCONNECTED = "provider.tts.disconnected"
    PROVIDER_TTS_FAILED = "provider.tts.failed"
    PROVIDER_REALTIME_CONNECTED = "provider.realtime.connected"
    PROVIDER_REALTIME_DISCONNECTED = "provider.realtime.disconnected"
    PROVIDER_REALTIME_FAILED = "provider.realtime.failed"
